<?php

namespace Tests\Unit;

use App\Category;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class CategoryTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->c = Category::all()->random();
    }

    /**
     * Check if category is linked to a project.
     *
     * @return void
     */
    public function testProjects()
    {
        $this->assertInstanceOf('App\Project', $this->c->projects->first());
    }
}
