<?php

namespace Tests\Unit;

use App\Hour;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class HourTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->h = Hour::all()->random();
    }

    /**
     * test CreatedBy.
     *
     * @return void
     */
    public function testCreatedBy()
    {
        $this->assertInstanceOf('App\User',$this->h->createdBy);
    }

    /**
     * test CreatedBy.
     *
     * @return void
     */
    public function testProject()
    {
        $this->assertInstanceOf('App\Project',$this->h->project);
    }
}
