<?php

namespace Tests\Unit;

use App\Location;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class LocationTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->l = Location::all()->random();
    }

    /**
     * Test if Location belongs to company.
     *
     * @return void
     */
    public function testCompany()
    {
        $this->assertInstanceOf('App\Company', $this->l->company);
    }
}
