<?php

namespace Tests\Unit;

use App\Project;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ProjectTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->p = Project::all()->random();
    }

    /**
     * Test if project is created by
     *
     * @return void
     */
    public function testCreatedBy()
    {
        $this->assertInstanceOf('App\User', $this->p->createdBy);
    }

    /**
     * Test for the responsible user
     *
     * @return void
     */
    public function testResponsibleUser()
    {
        $this->assertInstanceOf('App\User', $this->p->responsibleUser);
    }

    /**
     * Test for the hoursBooked
     *
     * @return void
     */
    public function testhoursBooked()
    {
        $this->assertInstanceOf('App\Hour', $this->p->hoursBooked->first());
    }

    /**
     * Test for the companies
     *
     * @return void
     */
    public function testcompanies()
    {
        $this->assertInstanceOf('App\Company', $this->p->companies->first());
    }

    /**
     * Test for the companies
     *
     * @return void
     */
    public function testcategories()
    {
        $this->assertInstanceOf('App\Category', $this->p->categories->first());
    }


}
