<?php

namespace Tests\Unit;

use App\Rule;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class RuleTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->r = Rule::all()->random();
    }

    /**
     * A basic unit test to check createdBy
     *
     * @return void
     */
    public function testCreatedBy()
    {
        $this->assertInstanceOf('App\User', $this->r->createdBy);
    }
}
